# Form implementation generated from reading ui file 'Reviewer.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Reviewer(object):
    def setupUi(self, Reviewer):
        Reviewer.setObjectName("Reviewer")
        Reviewer.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Reviewer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFrom = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelFrom.setFont(font)
        self.labelFrom.setObjectName("labelFrom")
        self.horizontalLayout.addWidget(self.labelFrom)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelData = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelData.setFont(font)
        self.labelData.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelData.setObjectName("labelData")
        self.horizontalLayout.addWidget(self.labelData)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelSubject = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelSubject.setFont(font)
        self.labelSubject.setObjectName("labelSubject")
        self.verticalLayout.addWidget(self.labelSubject)
        self.textMail = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textMail.setFont(font)
        self.textMail.setObjectName("textMail")
        self.verticalLayout.addWidget(self.textMail)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        Reviewer.setCentralWidget(self.centralwidget)

        self.retranslateUi(Reviewer)
        QtCore.QMetaObject.connectSlotsByName(Reviewer)

    def retranslateUi(self, Reviewer):
        _translate = QtCore.QCoreApplication.translate
        Reviewer.setWindowTitle(_translate("Reviewer", "Reviewer"))
        self.labelFrom.setText(_translate("Reviewer", "From"))
        self.labelData.setText(_translate("Reviewer", "TextLabel"))
        self.labelSubject.setText(_translate("Reviewer", "Subject"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Reviewer = QtWidgets.QMainWindow()
    ui = Ui_Reviewer()
    ui.setupUi(Reviewer)
    Reviewer.show()
    sys.exit(app.exec())
